Repository wizzie-io/wizz-vis, pull requests merged in 2018-12, with the labels that each got.

#234 WIZZIE-3069: Add documentation about granularity.
  docs/guides/widgets.md
Labels: feature

#238 WIZZIE-3095: Default granularity tests.
  spec/controllers/widgets_controller_spec.rb
  spec/factories/widgets.rb
Labels: improvements

#240 WIZZIE-3158: Fix the discovery of the dimensions in the Multiserie widget.
  app/models/widget.rb
  app/models/widget_multiserie.rb
Labels: bug

#241 WIZZIE-3162: Fix legend ticks visibility.
  app/javascript/wizz-vis/utils/graph.js
Labels: bug

#242 WIZZIE-3172: Fix JS errors for fullscreen.
  app/assets/javascripts/fullscreen.js
Labels: bug

#243 WIZZIE-3219: fix error persisting global time interval at DB.
  .circleci/config.yml
  app/javascript/wizz-vis/components/controls/MenuRange.jsx
Labels: bug
