Repository wizzie-io/wizz-vis, pull requests merged in 2018-09, with the labels that each got.

#164 WIZZIE-2459: Upgrade rubyzip gem due to security issue.
  Gemfile.lock
Labels: bug

#160 WIZZIE-2417: New widget to show text.
  app/assets/stylesheets/components/widgets/_widget_text.scss
  app/assets/stylesheets/components/widgets/_widgets.scss
  app/javascript/wizz-vis/components/WidgetBase.jsx
  app/javascript/wizz-vis/components/widgets/WidgetText.jsx
  app/javascript/wizz-vis/components/widgets/WidgetValue.jsx
  app/javascript/wizz-vis/utils/format.js
  app/models/widget_text.rb
  app/serializers/api/v1/widget_text_serializer.rb
Labels: feature

#162 WIZZIE-2413: Change the caching system to Redis.
  Gemfile
  Gemfile.lock
  config/environments/production.rb
Labels: feature

#163 WIZZIE-2421: Improve Heatmap colors updates.
  app/javascript/wizz-vis/components/widgets/WidgetHeatmap.jsx
Labels: improvements

#161 WIZZIE-2422: Fix the Value widget with compare enabled and -Infinity druid value.
  app/javascript/wizz-vis/utils/format.js
Labels: bug

#166 WIZZIE-2424: Login on Wizz-vis with the Wizz-in credentials.
  .codebeatignore
  .env
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/pages/_login.scss
  app/assets/stylesheets/pages/pages.scss
  app/controllers/application_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/sessions_controller.rb
  app/models/user.rb
  app/views/layouts/_header.html.erb
  app/views/layouts/login.html.erb
  app/views/users/sessions/new.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20180816121249_devise_create_users.rb
  db/schema.rb
  lib/omniauth/strategies/doorkeeper.rb
  package-lock.json
  scripts/docker-entrypoint-web-prod.sh
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: feature

#167 WIZZIE-2463: fix assignation of marker's color at WidgetPlaneLocation
  app/javascript/wizz-vis/components/widgets/WidgetPlaneLocation.jsx
Labels: bug

#165 WIZZIE-2411: Include PropTypes at React widget components.
  app/javascript/wizz-vis/components/Clock.jsx
  app/javascript/wizz-vis/components/Dashboard.jsx
  app/javascript/wizz-vis/components/Info.jsx
  app/javascript/wizz-vis/components/PlaneRoute.jsx
  app/javascript/wizz-vis/components/ResumeValue.jsx
  app/javascript/wizz-vis/components/WidgetBase.jsx
  app/javascript/wizz-vis/components/widgets/WidgetBar.jsx
  app/javascript/wizz-vis/components/widgets/WidgetChord.jsx
  app/javascript/wizz-vis/components/widgets/WidgetDrilldown.jsx
  app/javascript/wizz-vis/components/widgets/WidgetHeatmap.jsx
  app/javascript/wizz-vis/components/widgets/WidgetHistogram.jsx
  app/javascript/wizz-vis/components/widgets/WidgetImage.jsx
  app/javascript/wizz-vis/components/widgets/WidgetLocation.jsx
  app/javascript/wizz-vis/components/widgets/WidgetMultiserie.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPie.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlane.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneLocation.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneRoute.jsx
  app/javascript/wizz-vis/components/widgets/WidgetRefresh.jsx
  app/javascript/wizz-vis/components/widgets/WidgetResume.jsx
  app/javascript/wizz-vis/components/widgets/WidgetRoute.jsx
  app/javascript/wizz-vis/components/widgets/WidgetSankey.jsx
  app/javascript/wizz-vis/components/widgets/WidgetSerie.jsx
  app/javascript/wizz-vis/components/widgets/WidgetTable.jsx
  app/javascript/wizz-vis/components/widgets/WidgetText.jsx
  app/javascript/wizz-vis/components/widgets/WidgetTitle.jsx
  app/javascript/wizz-vis/components/widgets/WidgetTrash.jsx
  app/javascript/wizz-vis/components/widgets/WidgetValue.jsx
  app/javascript/wizz-vis/props/index.js
Labels: feature

#168 WIZZIE-2502: Update README.md
  Procfile.dev
  README.md
Labels: improvements

#172 WIZZIE-2500 && WIZZIE-2513: Add a legend at Heatmap and Plane widgets.
  app/assets/stylesheets/components/widgets/_widget_legend.scss
  app/assets/stylesheets/components/widgets/_widgets.scss
  app/javascript/wizz-vis/components/Legend.jsx
  app/javascript/wizz-vis/components/widgets/WidgetHeatmap.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlane.jsx
  app/javascript/wizz-vis/utils/graph.js
  package.json
  yarn.lock
Labels: feature

#174 WIZZIE-2489: Improve wizz-vis login interface design.
  app/assets/images/divider-powered.png
  app/assets/images/login_notebook.png
  app/assets/images/logo_wizzvis.png
  app/assets/stylesheets/pages/_login.scss
  app/assets/stylesheets/pages/_login.scss.erb
  app/views/layouts/login.html.erb
Labels: improvements

#178 WIZZIE-2554: Move login feature out of Wizz-Vis
  .env
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/widgets_controller.rb
  app/models/user.rb
  app/views/layouts/_header.html.erb
  app/views/layouts/_sidebar.html.erb
  app/views/users/sessions/new.html.erb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20180816121249_devise_create_users.rb
  db/schema.rb
  lib/omniauth/strategies/doorkeeper.rb
  plugins/.keep
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: feature
