Repository wizzie-io/wizz-vis, pull requests merged in 2018-08, with the labels that each got.

#141 WIZZIE-2317: Include the date for past series.
  app/javascript/wizz-vis/utils/compare.js
  app/javascript/wizz-vis/utils/time.js
Labels: improvements

#145 WIZZIE-2358: fix error on sidekiq-cron gem
  Gemfile
  Gemfile.lock
Labels: bug

#148 WIZZIE-2370: Fix error on xAxis when interval is about yesterday or last year.
  app/javascript/wizz-vis/utils/time.js
Labels: bug

#144 WIZZIE-2325: WidgetPlaneRoute to represent routes hover an image.
  app/javascript/wizz-vis/components/PlaneRoute.jsx
  app/javascript/wizz-vis/components/WidgetBase.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneRoute.jsx
  app/javascript/wizz-vis/utils/colors.js
  app/javascript/wizz-vis/utils/gps.js
  app/models/widget_plane_route.rb
  package.json
  yarn.lock
Labels: feature

#147 WIZZIE-2326: new PlaneLocation widget.
  app/javascript/wizz-vis/components/WidgetBase.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneLocation.jsx
  app/models/widget_plane_location.rb
  lib/datastore/query.rb
  yarn.lock
Labels: feature

#150 WIZZIE-2371: fix keep_ratio option at WidgetPlaneRoute.
  app/javascript/wizz-vis/components/widgets/WidgetImage.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneRoute.jsx
Labels: bug

#149 WIZZIE-2372: Fix keep_ratio option at WidgetPlaneLocation.
  app/javascript/wizz-vis/components/widgets/WidgetPlaneLocation.jsx
  yarn.lock
Labels: improvements

#146 WIZZIE-2319: Add the compare option to the table widget.
  app/javascript/wizz-vis/components/widgets/WidgetResume.jsx
  app/javascript/wizz-vis/components/widgets/WidgetTable.jsx
  app/models/widget_table.rb
Labels: feature

#153 WIZZIE-2112: update docker push process
  .circleci/config.yml
Labels: improvements

#151 WIZZIE-2375: improve calculations on ResumeValue component.
  app/javascript/wizz-vis/components/ResumeValue.jsx
  app/javascript/wizz-vis/components/widgets/WidgetResume.jsx
  app/javascript/wizz-vis/components/widgets/WidgetTable.jsx
  app/javascript/wizz-vis/components/widgets/WidgetValue.jsx
  app/javascript/wizz-vis/utils/format.js
Labels: improvements

#152 WIZZIE-2365: marker color depending on metric at WidgetPlaneLocation.
  app/javascript/wizz-vis/components/widgets/WidgetPlaneLocation.jsx
Labels: feature

#154 Include API serializers for some widgets.
  app/serializers/api/v1/widget_histogram_serializer.rb
  app/serializers/api/v1/widget_plane_location_serializer.rb
  app/serializers/api/v1/widget_plane_route_serializer.rb
Labels: bug

#155 WIZZIE-2382: get correct data for compare interval at WidgetValue.
  app/javascript/wizz-vis/components/widgets/WidgetValue.jsx
Labels: bug

#157 Bug: fix error when the plane loaded for WidgetPlaneRoute take time.
  .codebeatignore
  app/javascript/wizz-vis/components/PlaneRoute.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneRoute.jsx
Labels: bug, check

#159 WIZZIE-2419: Add threshold lines at Histogram widgets.
  app/javascript/wizz-vis/components/widgets/WidgetHistogram.jsx
Labels: feature
