Repository wizzie-io/wizz-vis, pull requests merged in 2018-11, with the labels that each got.

#212 WIZZIE-2838: round on hyperunique metrics by default.
  config/initializers/ruby_druid.rb
Labels: improvements

#211 WIZZIE-3835: reduce webpack bundle size for production.
  app/javascript/wizz-vis/components/widgets/WidgetImage.jsx
  app/javascript/wizz-vis/components/widgets/WidgetSankey.jsx
  app/javascript/wizz-vis/components/widgets/WidgetValue.jsx
  app/javascript/wizz-vis/utils/gps.js
  config/initializers/react_on_rails.rb
  config/webpack/environment.js
  config/webpack/production.js
  package.json
Labels: improvements

#213 WIZZIE-2843: Fix error on main link at WidgetImage.
  app/javascript/wizz-vis/components/widgets/WidgetImage.jsx
Labels: bug

#214 WIZZIE-2849: import castArray lodash library at locatable.js
  app/javascript/wizz-vis/models/locatable.js
Labels: bug

#219 WIZZIE-2865: create a component for error catching.
  Gemfile.lock
  app/javascript/wizz-vis/components/ErrorBoundary.jsx
  app/javascript/wizz-vis/components/WidgetBase.jsx
Labels: bug

#218 WIZZIE-2863: Increase the font weight to the text on the navbar menu.
  app/assets/stylesheets/components/_navbar.scss
Labels: improvements

#207 WIZZIE-2826: Homogenize the attribute metrics for all Widgets.
  app/javascript/wizz-vis/components/widgets/WidgetBar.jsx
  app/javascript/wizz-vis/components/widgets/WidgetChord.jsx
  app/javascript/wizz-vis/components/widgets/WidgetHeatmap.jsx
  app/javascript/wizz-vis/components/widgets/WidgetHistogram.jsx
  app/javascript/wizz-vis/components/widgets/WidgetMultiserie.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPie.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlane.jsx
  app/javascript/wizz-vis/components/widgets/WidgetSankey.jsx
  app/javascript/wizz-vis/components/widgets/WidgetValue.jsx
  app/javascript/wizz-vis/utils/format.js
  docs/guides/widgets.md
Labels: improvements

#216 WIZZIE-2853: Update the dashboard associated to a widget through the API.
  app/controllers/api/v1/widgets_controller.rb
Labels: improvements

#220 WIZZIE-2869: config the opacity, radius and max value of WidgetPlane's heatmap.
  app/javascript/wizz-vis/components/widgets/WidgetPlane.jsx
  app/javascript/wizz-vis/vendor/ReactHeatmap.js
  app/javascript/wizz-vis/vendor/heatmapjs/build/heatmap.js
  docs/guides/widgets.md
Labels: feature

#222 WIZZIE-2744: fix error on WidgetMultiserie when only one timestamp point
  app/javascript/wizz-vis/components/widgets/WidgetMultiserie.jsx
Labels: bug

#223 WIZZIE-2911: numeric validations for col, row, size_x and size_y.
  app/models/widget.rb
  spec/models/widget_spec.rb
Labels: bug

#224 WIZZIE-2876: extend the color palette used on graphs.
  app/javascript/wizz-vis/utils/colors.js
Labels: improvements

#226 WIZZIE-3043: Allow use date inputs at global interval (Safari).
  app/assets/stylesheets/components/_menus.scss
Labels: bug

#228 WIZZIE-3048 && WIZZIE-3049: History back feature when clicking on a WidgetImage.
  app/javascript/wizz-vis/components/ImageLink.jsx
  docs/guides/widgets.md
Labels: feature

#227 WIZZIE-3051 && WIZZIE-3053: Add option for show/hide legend at Heatmap and Plane.
  app/javascript/wizz-vis/components/widgets/WidgetHeatmap.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlane.jsx
  docs/guides/widgets.md
Labels: feature

#233 WIZZIE-3035: Add support to manage enterprise builds
  .circleci/config.yml
Labels: improvements

#231 WIZZIE-3055: Dashboard and filters association.
  app/controllers/api/v1/dashboards_controller.rb
  app/controllers/api/v1/widgets_controller.rb
  app/models/dashboard.rb
  app/models/docs/dashboard.rb
  app/models/widget.rb
  app/serializers/api/v1/dashboard_serializer.rb
  app/serializers/dashboard_serializer.rb
  config/routes/api.rb
  docs/api/endpoints.md
  lib/api/dashboard_api.rb
  spec/controllers/api/v1/dashboards_controller_spec.rb
  spec/factories/filters.rb
  spec/models/dashboard_spec.rb
  spec/models/widget_spec.rb
Labels: feature

#236 WIZZIE-3092: upgrade rails version due to vulnerability advisors.
  Gemfile
  Gemfile.lock
Labels: bug

#230 WIZZIE-3067: Force granularity to all for those widgets which need it.
  app/models/widget.rb
  app/models/widget_bar.rb
  app/models/widget_chord.rb
  app/models/widget_heatmap.rb
  app/models/widget_histogram.rb
  app/models/widget_pie.rb
  app/models/widget_plane.rb
  app/models/widget_sankey.rb
  app/models/widget_table.rb
Labels: improvements
