Repository wizzie-io/wizz-vis, pull requests merged in 2018-07, with the labels that each got.

#122 WIZZIE-2214: migrate ruby-druid repo.
  Gemfile
  Gemfile.lock
Labels: improvements

#124 WIZZIE-2224: Update version of gems with vulnerabilities
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  bin/webpack
  bin/webpack-dev-server
Labels: bug

#125 WIZZIE-2226: allow decimals at post aggregations.
  lib/datastore/post_aggregators.rb
Labels: bug

#129 WIZZIE-2238: fix params processing for filters and aggregators.
  lib/api/widget_api.rb
  spec/controllers/api/v1/widgets_controller_spec.rb
Labels: bug

#126 WIZZIE-2215: datasketch support
  Gemfile.lock
  lib/datastore/post_aggregators.rb
  spec/factories/aggregators.rb
  spec/factories/dimensions.rb
  spec/factories/post_aggregators.rb
  spec/lib/datastore/query_spec.rb
Labels: feature

#123 WIZZIE-2213: Add the compare option to the Serie widget.
  app/assets/stylesheets/components/widgets/_widget_compare.scss
  app/assets/stylesheets/components/widgets/_widgets.scss
  app/javascript/wizz-vis/components/widgets/WidgetResume.jsx
  app/javascript/wizz-vis/components/widgets/WidgetSerie.jsx
  app/javascript/wizz-vis/utils/array.js
  app/javascript/wizz-vis/utils/compare.js
  app/models/concerns/intervalable.rb
  app/models/widget.rb
  app/serializers/widget_serializer.rb
  lib/datastore/query.rb
  spec/lib/datastore/query_spec.rb
Labels: feature

#130 WIZZIE-2241: compare feature for Value widget.
  app/javascript/wizz-vis/components/ResumeValue.jsx
  app/javascript/wizz-vis/components/widgets/WidgetResume.jsx
  app/javascript/wizz-vis/components/widgets/WidgetSerie.jsx
  app/javascript/wizz-vis/components/widgets/WidgetValue.jsx
  app/javascript/wizz-vis/utils/compare.js
Labels: feature

#134 WIZZIE-2266: fix datasketch agg when there are no aggegator filters.
  lib/datastore/aggregators.rb
  spec/lib/datastore/query_spec.rb
Labels: bug

#133 WIZZIE-2267: fix error when compare and granularity 'all' for Value widget
  app/models/concerns/intervalable.rb
  app/models/widget_value.rb
Labels: bug

#132 WIZZIE-2265: improve compare series for Serie widget.
  app/javascript/wizz-vis/components/widgets/WidgetSerie.jsx
Labels: improvements

#136 Include COMMIT file with the ID of last commit.
  .circleci/config.yml
Labels: improvements

#138 Fix interval at dimension aggregator worker.
  app/workers/dimension_aggregator_worker.rb
Labels: bug

#139 WIZZIE-2316: Show dimension and metric at markers at Location widgets.
  app/assets/stylesheets/components/widgets/_widget_location.scss
  app/javascript/wizz-vis/components/widgets/WidgetLocation.jsx
Labels: improvements

#143 WIZZIE-2283: round Time.now to seconds.
  config/initializers/time.rb
  spec/initializers/time_spec.rb
Labels: bug

#142 WIZZIE-2245: include previous_period as compare option.
  app/javascript/wizz-vis/components/widgets/WidgetResume.jsx
  app/javascript/wizz-vis/components/widgets/WidgetSerie.jsx
  app/javascript/wizz-vis/utils/compare.js
  app/javascript/wizz-vis/utils/time.js
  app/models/concerns/intervalable.rb
Labels: improvements

#140 WIZZIE-2318: fix error merging data from interval and compare interval.
  app/javascript/wizz-vis/utils/array.js
  app/javascript/wizz-vis/utils/compare.js
Labels: bug
