Repository wizzie-io/wizz-vis, pull requests merged in 2018-10, with the labels that each got.

#173 WIZZIE-2493: Add a dashboard search bar at navbar.
  app/assets/stylesheets/components/_navbar.scss
  app/controllers/dashboards_controller.rb
  app/models/dashboard.rb
  app/views/dashboards/_pagination.html.erb
  app/views/dashboards/index.html.erb
  app/views/dashboards/index.js.erb
  app/views/dashboards/show.html.erb
  app/views/layouts/_header.html.erb
Labels: feature

#179 WIZZIE-2559: install plugins dependencies at docker build process.
  Dockerfile
Labels: bug

#180 WIZZIE-2570: inherit DocsController from ApplicationController.
  app/assets/stylesheets/components/_buttons.scss
  app/assets/stylesheets/components/_components.scss
  app/controllers/api/v1/docs_controller.rb
Labels: improvements

#181 Fix dashboard options after a search response.
  app/views/dashboards/index.js.erb
Labels: bug

#184 WIZZIE-2575: allow dynamic last time ranges.
  app/models/concerns/intervalable.rb
  docs/guides/widgets.md
  spec/concerns/intervalable_spec.rb
  spec/models/widget_spec.rb
Labels: improvements

#187 Reference documentation website at README file.
  README.md
Labels: documentation

#183 WIZZIE-2590_2591: fix heatmap and legend at WidgetHeatmap & WidgetPlane.
  Gemfile.lock
  app/assets/stylesheets/components/widgets/_widget_legend.scss
  app/javascript/wizz-vis/components/Legend.jsx
  app/javascript/wizz-vis/components/widgets/WidgetHeatmap.jsx
  app/javascript/wizz-vis/components/widgets/WidgetImage.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlane.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneLocation.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneRoute.jsx
  app/javascript/wizz-vis/utils/gps.js
  app/javascript/wizz-vis/utils/graph.js
Labels: bug

#189 WIZZIE-2675: fix error at WidgetValue w/ compare when there are filters.
  app/models/widget.rb
  spec/models/widget_spec.rb
Labels: bug

#186 WIZZIE-2600: stringFirst and stringLast aggregators support.
  Gemfile.lock
  lib/datastore/aggregators.rb
Labels: feature

#188 WIZZIE-2601: adapt map and plan widgets to work with stringLast and firstLast aggregators.
  app/javascript/wizz-vis/components/Routing.jsx
  app/javascript/wizz-vis/components/WidgetMarker.jsx
  app/javascript/wizz-vis/components/WidgetPopup.jsx
  app/javascript/wizz-vis/components/WidgetPopupElement.jsx
  app/javascript/wizz-vis/components/widgets/WidgetLocation.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneLocation.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneRoute.jsx
  app/javascript/wizz-vis/components/widgets/WidgetRoute.jsx
  app/javascript/wizz-vis/models/locatable.js
  app/models/aggregator.rb
  app/models/concerns/widget_locatable.rb
  app/models/concerns/widget_routeable.rb
  app/models/widget_location.rb
  app/models/widget_plane_location.rb
  app/models/widget_plane_route.rb
  app/models/widget_route.rb
Labels: feature

#191 WIZZIE-2701: fix error for hidden enpoints at Wizz-Vis API.
  app/controllers/api/v1/docs_controller.rb
Labels: bug

#182 WIZZIE-2584: Add a widget time selector to the navbar.
  app/assets/stylesheets/components/_components.scss
  app/assets/stylesheets/components/_menus.scss
  app/controllers/dashboards_controller.rb
  app/controllers/widgets_controller.rb
  app/javascript/wizz-vis/actions/index.js
  app/javascript/wizz-vis/components/Clock.jsx
  app/javascript/wizz-vis/components/Controls.jsx
  app/javascript/wizz-vis/components/Dashboard.jsx
  app/javascript/wizz-vis/components/WidgetBase.jsx
  app/javascript/wizz-vis/components/controls/FixedRange.jsx
  app/javascript/wizz-vis/components/controls/MenuRange.jsx
  app/javascript/wizz-vis/components/controls/RelativeRange.jsx
  app/javascript/wizz-vis/constants/index.js
  app/javascript/wizz-vis/containers/ControlsContainer.js
  app/javascript/wizz-vis/containers/DashboardContainer.js
  app/javascript/wizz-vis/index.js
  app/javascript/wizz-vis/reducers/functions/index.js
  app/javascript/wizz-vis/reducers/index.js
  app/javascript/wizz-vis/reducers/range.js
  app/javascript/wizz-vis/reducers/reload.js
  app/javascript/wizz-vis/startup/ControlsApp.jsx
  app/javascript/wizz-vis/startup/DashboardApp.jsx
  app/javascript/wizz-vis/startup/loader.jsx
  app/javascript/wizz-vis/store/index.js
  app/javascript/wizz-vis/utils/format.js
  app/javascript/wizz-vis/utils/time.js
  app/models/widget.rb
  app/views/dashboards/show.html.erb
  app/views/layouts/application.html.erb
  db/migrate/20181008100636_add_ranges_to_dashboard.rb
  db/schema.rb
  package.json
  spec/rails_helper.rb
  yarn.lock
Labels: feature

#192 WIZZIE-2742: fix error using global time range and compare feature.
  app/models/concerns/intervalable.rb
Labels: bug

#197 WIZZIE-2663: documentation for stringFirst and stringLast support.
  docs/guides/aggregators.md
  docs/guides/widgets.md
Labels: documentation

#190 WIZZIE-2605: Include a button to allow fullscreen mode for dashboards.
  app/assets/javascripts/fullscreen.js
  app/assets/stylesheets/dashboards.scss
  app/helpers/application_helper.rb
  app/javascript/wizz-vis/components/Controls.jsx
  app/views/dashboards/show.html.erb
Labels: feature

#193 WIZZIE-2752: time range in the title if a widget has overrided it.
  app/assets/stylesheets/colors.scss.erb
  app/assets/stylesheets/components/_menus.scss
  app/assets/stylesheets/components/widgets/_widgets.scss
  app/javascript/wizz-vis/components/IntervalInfo.jsx
  app/javascript/wizz-vis/components/WidgetBase.jsx
  app/javascript/wizz-vis/components/widgets/WidgetTitle.jsx
  app/javascript/wizz-vis/utils/time.js
  app/models/widget.rb
  app/serializers/widget_serializer.rb
Labels: improvements

#194 WIZZIE-2755: Add start/end/range time validations.
  app/javascript/wizz-vis/components/controls/FixedRange.jsx
  app/javascript/wizz-vis/components/controls/RelativeRange.jsx
  app/models/concerns/intervalable.rb
  app/models/widget.rb
Labels: improvements

#198 WIZZIE-2775: Add time intervals to the API.
  app/controllers/api/v1/dashboards_controller.rb
  app/models/docs/dashboard.rb
  app/serializers/api/v1/dashboard_serializer.rb
  app/serializers/dashboard_serializer.rb
Labels: feature

#201 WIZZIE-2802: Update documentation about dashboards in the Endpoints s…
  docs/api/endpoints.md
Labels: documentation

#199 WIZZIE-2801: Fix FS in Safari.
  app/assets/stylesheets/dashboards.scss
Labels: bug

#202 WIZZIE-2716: improve Wizz-Vis documentation.
  docs/guides/widgets.md
Labels: documentation

#203 WIZZIE-2820: Primary Color for dashboard's pagination.
  app/views/kaminari/_page.html.erb
Labels: bug

#209 WIZZIE-2831: update version of loofah gem due to vulnerability issue.
  Gemfile.lock
Labels: bug

#200 WIZZIE-2750: add link support to WidgetImage.
  app/javascript/wizz-vis/components/ImageLink.jsx
  app/javascript/wizz-vis/components/widgets/WidgetImage.jsx
  docs/guides/widgets.md
Labels: feature

#204 WIZZIE-2822: Fix intervalAttributes object when no start_time/end_time is setted.
  app/models/widget.rb
Labels: bug

#205 WIZZIE-2793: Fix long texts at WidgetTable.
  app/assets/stylesheets/components/widgets/_widget_table.scss
Labels: improvements

#206 WIZZIE-2825: Fix text inputs at Fixed interval selector.
  app/assets/stylesheets/components/_menus.scss
Labels: bug
