Repository wizzie-io/wizz-vis, pull requests merged in 2019-01, with the labels that each got.

#244 WIZZIE-3231: improve the navigation bars, making them thinner.
  app/assets/stylesheets/components/_filters.scss
  app/assets/stylesheets/components/_inputs.scss
  app/assets/stylesheets/components/_navbar.scss
  app/views/dashboards/index.html.erb
  app/views/dashboards/show.html.erb
  app/views/layouts/_theme.html.erb
Labels: improvements

#245 WIZZIE-3323: prevent one finger dragging on maps for mobile devices.
  .circleci/config.yml
  app/javascript/wizz-vis/components/widgets/WidgetHeatmap.jsx
  app/javascript/wizz-vis/components/widgets/WidgetLocation.jsx
  package.json
  yarn.lock
Labels: improvements

#248 WIZZIE-3321: Improve the global dimension filters for different screen resolutions.
  app/assets/stylesheets/components/_filters.scss
Labels: bug

#247 WIZZIE-3311: Create the error pages for 400, 404 and 500 errors.
  app/assets/stylesheets/pages/_errors.scss.erb
  app/assets/stylesheets/pages/pages.scss
  app/controllers/errors_controller.rb
  app/views/errors/400.html.erb
  app/views/errors/404.html.erb
  app/views/errors/500.html.erb
  app/views/layouts/_error.html.erb
  config/environments/production.rb
  config/routes.rb
  public/400.html
  public/404.html
  public/500.html
Labels: feature

#246 WIZZIE-3298: Create a dropdown menu with options to edit, reload and fs.
  app/assets/javascripts/fullscreen.js
  app/assets/stylesheets/components/_menus.scss
  app/assets/stylesheets/dashboards.scss
  app/javascript/wizz-vis/components/Controls.jsx
  app/javascript/wizz-vis/components/controls/Fullscreen.jsx
  app/javascript/wizz-vis/components/controls/MenuRange.jsx
  app/javascript/wizz-vis/components/controls/Reload.jsx
Labels: feature

#249 WIZZIE-3355: upgrade version of packages due to security vulnerabilities
  package.json
  yarn.lock
Labels: bug

#250 WIZZIE-3365: widget option for showing the time interval in widget title.
  app/javascript/wizz-vis/components/WidgetBase.jsx
  app/javascript/wizz-vis/components/widgets/WidgetTitle.jsx
Labels: improvements

#251 [Wizz-Vis] Adapt the menu components to the new FloatMenu component.
  app/assets/stylesheets/components/_menus.scss
  app/javascript/wizz-vis/components/Controls.jsx
  app/javascript/wizz-vis/components/controls/MenuOptions.jsx
  app/javascript/wizz-vis/components/controls/MenuRange.jsx
Labels: improvements

#252 [Wizz-Vis] Group the filter components.
  app/javascript/wizz-vis/components/Filters.jsx
  app/javascript/wizz-vis/components/filters/AddFilter.jsx
  app/javascript/wizz-vis/components/filters/FilterItem.jsx
  app/javascript/wizz-vis/components/filters/FilterItems.jsx
  app/javascript/wizz-vis/components/filters/FilterMenu.jsx
  app/javascript/wizz-vis/components/filters/FilterOperatorDropdown.jsx
  app/javascript/wizz-vis/components/filters/OverFlowFilters.jsx
Labels: improvements

#255 Include Wizz-Vis logo in the README
  README.md
Labels: improvements

#253 [Wizz-Vis] Group the widget components.
  app/javascript/wizz-vis/components/ErrorBoundary.jsx
  app/javascript/wizz-vis/components/widgets/WidgetBar.jsx
  app/javascript/wizz-vis/components/widgets/WidgetChord.jsx
  app/javascript/wizz-vis/components/widgets/WidgetHeatmap.jsx
  app/javascript/wizz-vis/components/widgets/WidgetHistogram.jsx
  app/javascript/wizz-vis/components/widgets/WidgetLocation.jsx
  app/javascript/wizz-vis/components/widgets/WidgetMultiserie.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPie.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlane.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneLocation.jsx
  app/javascript/wizz-vis/components/widgets/WidgetPlaneRoute.jsx
  app/javascript/wizz-vis/components/widgets/WidgetRoute.jsx
  app/javascript/wizz-vis/components/widgets/WidgetSankey.jsx
  app/javascript/wizz-vis/components/widgets/WidgetSerie.jsx
  app/javascript/wizz-vis/components/widgets/WidgetTable.jsx
  app/javascript/wizz-vis/components/widgets/WidgetText.jsx
  app/javascript/wizz-vis/components/widgets/WidgetTitle.jsx
  app/javascript/wizz-vis/components/widgets/WidgetValue.jsx
  app/javascript/wizz-vis/components/widgets/utils/Drilldown.jsx
  app/javascript/wizz-vis/components/widgets/utils/Info.jsx
  app/javascript/wizz-vis/components/widgets/utils/IntervalInfo.jsx
  app/javascript/wizz-vis/components/widgets/utils/Legend.jsx
  app/javascript/wizz-vis/components/widgets/utils/PlaneRoute.jsx
  app/javascript/wizz-vis/components/widgets/utils/PopupElement.jsx
  app/javascript/wizz-vis/components/widgets/utils/Refresh.jsx
  app/javascript/wizz-vis/components/widgets/utils/Resume.jsx
  app/javascript/wizz-vis/components/widgets/utils/ResumeValue.jsx
  app/javascript/wizz-vis/components/widgets/utils/Routing.jsx
  app/javascript/wizz-vis/components/widgets/utils/Trash.jsx
  app/javascript/wizz-vis/components/widgets/utils/WidgetMarker.jsx
  app/javascript/wizz-vis/components/widgets/utils/WidgetPopup.jsx
  app/javascript/wizz-vis/index.js
Labels: improvements

#256 WIZZIE-3382: move the login files to a plugin.
  app/assets/images/divider-powered.png
  app/assets/images/login_notebook.png
  app/assets/stylesheets/dashboards.scss
  app/assets/stylesheets/pages/_login.scss.erb
  app/assets/stylesheets/pages/pages.scss
  app/helpers/application_helper.rb
  app/views/dashboards/show.html.erb
  app/views/layouts/login.html.erb
  config/application.rb
Labels: feature

#257 WIZZIE-3492: Fix the widget Heatmap visualization if errors.
  app/javascript/wizz-vis/components/widgets/WidgetHeatmap.jsx
Labels: bug
